apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: custom-fastapi-service
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/h-t-d-a-f-a-t-g-c-r/custom-fastapi/custom-fastapi:latest
          env:
          ports:
            - containerPort: 4000